### ISSUE TITLE
Block about google drive app

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/www.iiifhosting.com#11]
We need to add information about google drive app. Add links to google drive. Following text draft:

## IIIF from images in Google Drive
 
Google Drive meets #IIIF: click on JPEG or TIFF files in Drive and get a #IIIF viewer.
Double click on a JPEG or TIFF in your Google Drive and get #IIIF! Link to a chrome web store.
Digital humanities students using Chromebooks? Turn a JPEG or TIFF on your drive into IIIF and use it in Mirador or other tools! #digitalhumanities #iiif

**Comment by daliborjanak** [comment]
@petrsloup can you post here links to store, please?

**Comment by petrsloup** [comment]
- Chrome Web Store extension
  - https://chrome.google.com/webstore/detail/iiifhosting/olcdbehgpggjnccbfgeclccdcnnlanal
- Publish to the Google App Marketplace
   - https://gsuite.google.com/marketplace/app/iiifhosting/946611837451
