### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/www.iiifhosting.com#6]
Opening `iiifhosting.com` redirects to https://www.iiifhosting.com, which doesn't work.

**Comment by klokan** [comment]
https://github.com/klokantech/www.iiifhosting.com/commit/0e0addda109d22e1a81011554f3f612890a90857

https://github.com/klokantech/www.iiifhosting.com/commit/8527f4f096d68240353766116e8cfe50404a4568

https://github.com/klokantech/www.iiifhosting.com/commit/9913e87e93a2becf43c2dc5d3b7e4ce901b43511

**Comment by klokan** [comment]
https://github.com/klokantech/www.iiifhosting.com/commit/8527f4f096d68240353766116e8cfe50404a4568
